// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package jobStore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateJob(ctx context.Context, arg CreateJobParams) error
	DeleteJobById(ctx context.Context, id uuid.UUID) error
	GetAllJobs(ctx context.Context, arg GetAllJobsParams) ([]GetAllJobsRow, error)
	GetJobById(ctx context.Context, id uuid.UUID) (GetJobByIdRow, error)
	UpdateJobById(ctx context.Context, arg UpdateJobByIdParams) error
}

var _ Querier = (*Queries)(nil)
