// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package permissionStore

import (
	"context"
)

type Querier interface {
	AddPermissionForUserByIdAndCodes(ctx context.Context, arg AddPermissionForUserByIdAndCodesParams) error
	CreatePermission(ctx context.Context, code string) error
	DeletePermissionByCode(ctx context.Context, code string) error
	DeletePermissionForUserByIdAndCodes(ctx context.Context, arg DeletePermissionForUserByIdAndCodesParams) error
	GetPermissionsForUserByEmail(ctx context.Context, email string) ([]string, error)
	UpdatePermissionByCode(ctx context.Context, arg UpdatePermissionByCodeParams) error
}

var _ Querier = (*Queries)(nil)
