// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sadstore

type Sad struct {
	ID     int32  `db:"id" json:"id"`
	UserID int32  `db:"user_id" json:"user_id"`
	Name   string `db:"name" json:"name"`
	Reason string `db:"reason" json:"reason"`
}
