// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package userstore

import (
	"database/sql"
	"time"
)

type User struct {
	ID           int32          `db:"id" json:"id"`
	Name         string         `db:"name" json:"name"`
	Email        string         `db:"email" json:"email"`
	Role         string         `db:"role" json:"role"`
	Password     string         `db:"password" json:"password"`
	RefreshToken sql.NullString `db:"refresh_token" json:"refresh_token"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
}
